[package]
name = "eg-examples"
version = "0.1.0"
edition = "2018"
publish = false
license = "GPL3"

[dependencies]
embedded-graphics = "0.7.0"
embedded-graphics-simulator = "0.3.0"
micromath = { version = "1.1.0", default-features = false }
rand = "0.8"
ringbuffer = "0.8"

[dependencies.vario_display]
path = "../../core"
features = ["display_size_240x240"]
