[app]
elf = "target/thumbv7em-none-eabihf/release/vario"
addr_start = 0x0800_0000
addr_max = 0x0807_ffff

[copy]
elf = "scripts/copy_stm32f407_1m.elf"
addr_start = 0x0808_1000
addr_max = 0x0808_5fff

[image]
elf = "air-avionics_frontend_v0-3-7-0.elf"
name = "air-avionics_frontend_v0-3-7-0.bin"
addr_storage = 0x0808_0000
hw_version = "2.1.1.0"
sw_version = "0.3.7.0"
