[app]
elf = "target/thumbv7em-none-eabihf/release/vario"
addr_start = 0x0800_0000
addr_max = 0x0807_ffff

[copy]
elf = "scripts/copy_stm32h743_1m.elf"
addr_start = 0x0810_1000
addr_max = 0x0810_5fff

[image]
elf = "larus_frontend_v2_v0-3-8-0.elf"
name = "larus_frontend_v2_v0-3-8-0.bin"
addr_storage = 0x0810_0000
hw_version = "1.3.2.0"
sw_version = "0.3.8.0"
