use super::Editable;

impl Editable {
    pub fn name(&self) -> &'static str {
        match self {
            Editable::Bugs => "Bugs",
            Editable::Display => "Display",
            Editable::Glider => "Glider",
            Editable::McCready => "Mac Cready",
            Editable::None => "None",
            Editable::PilotWeight => "Pilot Weight",
            Editable::Return => "Return",
            Editable::TcClimbRate => "TC Climb Rate",
            Editable::TcSpeedToFly => "TC Speed to Fly",
            Editable::Theme => "Theme",
            Editable::VarioModeControl => "Vario Control",
            Editable::Volume => "Volume",
            Editable::WaterBallast => "Water Ballast",
            Editable::Info1 => "Info 1 Content",
            Editable::Info2 => "Info 2 Content",
            Editable::Rotation => "Display Rotation",
            Editable::CenterFrequency => "Center Frequency",
            Editable::CenterViewCircling => "Center Circling",
            Editable::CenterViewStraight => "Center Straight",
            Editable::ResetConfig => "Config Reset",
            Editable::UserProfile => "User Profile",
            Editable::EmptyMass => "Empty Mass",
            Editable::MaxBallast => "Max Ballast",
            Editable::ReferenceWeight => "Reference Weight",
            Editable::PolarValueV1 => "Polar V 1",
            Editable::PolarValueV2 => "Polar V 2",
            Editable::PolarValueV3 => "Polar V 3",
            Editable::PolarValueSi1 => "Polar Si 1",
            Editable::PolarValueSi2 => "Polar Si 2",
            Editable::PolarValueSi3 => "Polar Si 3",
            Editable::GliderSymbol => "Glider Symbol",
            Editable::BatteryGood => "Battery good",
            Editable::BatteryBad => "Battery bad",
            Editable::DrainPinConfig => "Drain Pin Config",
            Editable::FlowEmpty => "Lowest Flow",
            Editable::FlowSlope => "Flow Slope",
            Editable::FlashControl => "Flash Control",
            Editable::SpeedToFlyPinConfig => "STF Pin Config",
            Editable::GearPinConfig => "Gear Pin Config",
            Editable::AirbrakesPinConfig => "Airbrakes Pin Config",
            Editable::GearAlarmModeConfig => "Gear Alarm Config",
            Editable::AlarmVolume => "Alarm Volume",
            Editable::StfUpperLimit => "Stf Upper Limit",
            Editable::StfLowerLimit => "Stf Lower Limit",

            Editable::SensTiltRoll => "Sensor Tilt Roll",
            Editable::SensTiltPitch => "Sensor Tilt Pitch",
            Editable::SensTiltYaw => "Sensor Tilt Yaw",
            Editable::PitotOffset => "Pitot Offset",
            Editable::PitotSpan => "Pitot Span",
            Editable::QnhDelta => "QNH Delta",
            Editable::MagAutoCalib => "Mag Auto Calib",
            Editable::VarioTc => "Vario TC",
            Editable::VarioIntTc => "Vario Int TC",
            Editable::WindTc => "Wind TC",
            Editable::MeanWindTc => "Mean Wind TC",
            Editable::GnssConfig => "GNSS Config",
            Editable::AntBaselen => "Ant Base Len",
            Editable::AntSlaveDown => "Ant Slave Down",
            Editable::AntSlaveRight => "Ant Slave Right",
            Editable::CmdMeas1 => "Left Wing down",
            Editable::CmdMeas2 => "Right Wing down",
            Editable::CmdMeas3 => "Straight Flight",
            Editable::CmdCalcOrientation => "Calc Orientation",
            Editable::CmdFineTuneOrientation => "Fine Tune",
        }
    }
}
