// generated by create_corlors.py

#[repr(u8)]
#[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug)]
pub enum Colors {
    AliceBlue = 0,             // Rgb(240, 248, 255)
    AntiqueWhite = 1,          // Rgb(250, 235, 215)
    Aqua = 2,                  // Rgb(0, 255, 255)
    Aquamarine = 3,            // Rgb(127, 255, 212)
    Azure = 4,                 // Rgb(240, 255, 255)
    Beige = 5,                 // Rgb(245, 245, 220)
    Bisque = 6,                // Rgb(255, 228, 196)
    Black = 7,                 // Rgb(0, 0, 0)
    BlanchedAlmond = 8,        // Rgb(255, 235, 205)
    Blue = 9,                  // Rgb(0, 0, 255)
    BlueViolet = 10,           // Rgb(138, 43, 226)
    Brown = 11,                // Rgb(165, 42, 42)
    BurlyWood = 12,            // Rgb(222, 184, 135)
    CadetBlue = 13,            // Rgb(95, 158, 160)
    Chartreuse = 14,           // Rgb(127, 255, 0)
    Chocolate = 15,            // Rgb(210, 105, 30)
    Coral = 16,                // Rgb(255, 127, 80)
    CornflowerBlue = 17,       // Rgb(100, 149, 237)
    Cornsilk = 18,             // Rgb(255, 248, 220)
    Crimson = 19,              // Rgb(220, 20, 60)
    Cyan = 20,                 // Rgb(0, 255, 255)
    DarkBlue = 21,             // Rgb(0, 0, 139)
    DarkCyan = 22,             // Rgb(0, 139, 139)
    DarkGoldenrod = 23,        // Rgb(184, 134, 11)
    DarkGray = 24,             // Rgb(169, 169, 169)
    DarkGreen = 25,            // Rgb(0, 100, 0)
    DarkKhaki = 26,            // Rgb(189, 183, 107)
    DarkMagenta = 27,          // Rgb(139, 0, 139)
    DarkOliveGreen = 28,       // Rgb(85, 107, 47)
    DarkOrange = 29,           // Rgb(255, 140, 0)
    DarkOrchid = 30,           // Rgb(153, 50, 204)
    DarkRed = 31,              // Rgb(139, 0, 0)
    DarkSalmon = 32,           // Rgb(233, 150, 122)
    DarkSeaGreen = 33,         // Rgb(143, 188, 143)
    DarkSlateBlue = 34,        // Rgb(72, 61, 139)
    DarkSlateGray = 35,        // Rgb(47, 79, 79)
    DarkTurquoise = 36,        // Rgb(0, 206, 209)
    DarkViolet = 37,           // Rgb(148, 0, 211)
    DeepPink = 38,             // Rgb(255, 20, 147)
    DeepSkyBlue = 39,          // Rgb(0, 191, 255)
    DimGray = 40,              // Rgb(105, 105, 105)
    DodgerBlue = 41,           // Rgb(30, 144, 255)
    FireBrick = 42,            // Rgb(178, 34, 34)
    FloralWhite = 43,          // Rgb(255, 250, 240)
    ForestGreen = 44,          // Rgb(34, 139, 34)
    Gainsboro = 45,            // Rgb(220, 220, 220)
    GhostWhite = 46,           // Rgb(248, 248, 255)
    Gold = 47,                 // Rgb(255, 215, 0)
    Goldenrod = 48,            // Rgb(218, 165, 32)
    Gray = 49,                 // Rgb(128, 128, 128)
    Green = 50,                // Rgb(0, 128, 0)
    GreenYellow = 51,          // Rgb(173, 255, 47)
    Honeydew = 52,             // Rgb(240, 255, 240)
    HotPink = 53,              // Rgb(255, 105, 180)
    IndianRed = 54,            // Rgb(205, 92, 92)
    Indigo = 55,               // Rgb(75, 0, 130)
    Ivory = 56,                // Rgb(255, 255, 240)
    Khaki = 57,                // Rgb(240, 230, 140)
    Lavender = 58,             // Rgb(230, 230, 250)
    LavenderBlush = 59,        // Rgb(255, 240, 245)
    LawnGreen = 60,            // Rgb(124, 252, 0)
    LemonChiffon = 61,         // Rgb(255, 250, 205)
    LightBlue = 62,            // Rgb(173, 216, 230)
    LightCoral = 63,           // Rgb(240, 128, 128)
    LightCyan = 64,            // Rgb(224, 255, 255)
    LightGoldenrodYellow = 65, // Rgb(250, 250, 210)
    LightGray = 66,            // Rgb(211, 211, 211)
    LightGreen = 67,           // Rgb(144, 238, 144)
    LightPink = 68,            // Rgb(255, 182, 193)
    LightSalmon = 69,          // Rgb(255, 160, 122)
    LightSeaGreen = 70,        // Rgb(32, 178, 170)
    LightSkyBlue = 71,         // Rgb(135, 206, 250)
    LightSlateGray = 72,       // Rgb(119, 136, 153)
    LightSteelBlue = 73,       // Rgb(176, 196, 222)
    LightYellow = 74,          // Rgb(255, 255, 224)
    Lime = 75,                 // Rgb(0, 255, 0)
    LimeGreen = 76,            // Rgb(50, 205, 50)
    Linen = 77,                // Rgb(250, 240, 230)
    Magenta = 78,              // Rgb(255, 0, 255)
    Maroon = 79,               // Rgb(128, 0, 0)
    MediumAquamarine = 80,     // Rgb(102, 205, 170)
    MediumBlue = 81,           // Rgb(0, 0, 205)
    MediumOrchid = 82,         // Rgb(186, 85, 211)
    MediumPurple = 83,         // Rgb(147, 112, 219)
    MediumSeaGreen = 84,       // Rgb(60, 179, 113)
    MediumSlateBlue = 85,      // Rgb(123, 104, 238)
    MediumSpringGreen = 86,    // Rgb(0, 250, 154)
    MediumTurquoise = 87,      // Rgb(72, 209, 204)
    MediumVioletRed = 88,      // Rgb(199, 21, 133)
    MidnightBlue = 89,         // Rgb(25, 25, 112)
    MintCream = 90,            // Rgb(245, 255, 250)
    MistyRose = 91,            // Rgb(255, 228, 225)
    Moccasin = 92,             // Rgb(255, 228, 181)
    NavajoWhite = 93,          // Rgb(255, 222, 173)
    Navy = 94,                 // Rgb(0, 0, 128)
    OldLace = 95,              // Rgb(253, 245, 230)
    Olive = 96,                // Rgb(128, 128, 0)
    OliveDrab = 97,            // Rgb(107, 142, 35)
    Orange = 98,               // Rgb(255, 165, 0)
    OrangeRed = 99,            // Rgb(255, 69, 0)
    Orchid = 100,              // Rgb(218, 112, 214)
    PaleGoldenrod = 101,       // Rgb(238, 232, 170)
    PaleGreen = 102,           // Rgb(152, 251, 152)
    PaleTurquoise = 103,       // Rgb(175, 238, 238)
    PaleVioletRed = 104,       // Rgb(219, 112, 147)
    PapayaWhip = 105,          // Rgb(255, 239, 213)
    PeachPuff = 106,           // Rgb(255, 218, 185)
    Peru = 107,                // Rgb(205, 133, 63)
    Pink = 108,                // Rgb(255, 192, 203)
    Plum = 109,                // Rgb(221, 160, 221)
    PowderBlue = 110,          // Rgb(176, 224, 230)
    Purple = 111,              // Rgb(128, 0, 128)
    Red = 112,                 // Rgb(255, 0, 0)
    RosyBrown = 113,           // Rgb(188, 143, 143)
    RoyalBlue = 114,           // Rgb(65, 105, 225)
    SaddleBrown = 115,         // Rgb(139, 69, 19)
    Salmon = 116,              // Rgb(250, 128, 114)
    SandyBrown = 117,          // Rgb(244, 164, 96)
    SeaGreen = 118,            // Rgb(46, 139, 87)
    Seashell = 119,            // Rgb(255, 245, 238)
    Sienna = 120,              // Rgb(160, 82, 45)
    Silver = 121,              // Rgb(192, 192, 192)
    SkyBlue = 122,             // Rgb(135, 206, 235)
    SlateBlue = 123,           // Rgb(106, 90, 205)
    SlateGray = 124,           // Rgb(112, 128, 144)
    Snow = 125,                // Rgb(255, 250, 250)
    SpringGreen = 126,         // Rgb(0, 255, 127)
    SteelBlue = 127,           // Rgb(70, 130, 180)
    Tan = 128,                 // Rgb(210, 180, 140)
    Teal = 129,                // Rgb(0, 128, 128)
    Thistle = 130,             // Rgb(216, 191, 216)
    Tomato = 131,              // Rgb(255, 99, 71)
    Turquoise = 132,           // Rgb(64, 224, 208)
    Violet = 133,              // Rgb(238, 130, 238)
    Wheat = 134,               // Rgb(245, 222, 179)
    White = 135,               // Rgb(255, 255, 255)
    WhiteSmoke = 136,          // Rgb(245, 245, 245)
    Yellow = 137,              // Rgb(255, 255, 0)
    YellowGreen = 138,         // Rgb(154, 205, 50)
}

const MAX: u8 = 138;

use embedded_graphics::pixelcolor::{raw::RawU8, PixelColor};

impl PixelColor for Colors {
    type Raw = RawU8;
}

impl From<Colors> for RawU8 {
    fn from(color: Colors) -> RawU8 {
        RawU8::new(color as u8)
    }
}

use embedded_graphics::pixelcolor::{BinaryColor, Rgb888};
use embedded_graphics::prelude::WebColors;

impl From<Rgb888> for Colors {
    fn from(_color: Rgb888) -> Self {
        Colors::White
    }
}

impl From<BinaryColor> for Colors {
    fn from(_: BinaryColor) -> Self {
        Colors::White
    }
}

impl From<u8> for Colors {
    fn from(color: u8) -> Self {
        if color <= MAX {
            // Safety: We checked the range, so transmute is ok
            unsafe { core::mem::transmute::<u8, Colors>(color) }
        } else {
            Colors::Red // default Value to see something
        }
    }
}

impl From<Colors> for Rgb888 {
    fn from(val: Colors) -> Self {
        match val {
            Colors::AliceBlue => Rgb888::CSS_ALICE_BLUE,
            Colors::AntiqueWhite => Rgb888::CSS_ANTIQUE_WHITE,
            Colors::Aqua => Rgb888::CSS_AQUA,
            Colors::Aquamarine => Rgb888::CSS_AQUAMARINE,
            Colors::Azure => Rgb888::CSS_AZURE,
            Colors::Beige => Rgb888::CSS_BEIGE,
            Colors::Bisque => Rgb888::CSS_BISQUE,
            Colors::Black => Rgb888::CSS_BLACK,
            Colors::BlanchedAlmond => Rgb888::CSS_BLANCHED_ALMOND,
            Colors::Blue => Rgb888::CSS_BLUE,
            Colors::BlueViolet => Rgb888::CSS_BLUE_VIOLET,
            Colors::Brown => Rgb888::CSS_BROWN,
            Colors::BurlyWood => Rgb888::CSS_BURLY_WOOD,
            Colors::CadetBlue => Rgb888::CSS_CADET_BLUE,
            Colors::Chartreuse => Rgb888::CSS_CHARTREUSE,
            Colors::Chocolate => Rgb888::CSS_CHOCOLATE,
            Colors::Coral => Rgb888::CSS_CORAL,
            Colors::CornflowerBlue => Rgb888::CSS_CORNFLOWER_BLUE,
            Colors::Cornsilk => Rgb888::CSS_CORNSILK,
            Colors::Crimson => Rgb888::CSS_CRIMSON,
            Colors::Cyan => Rgb888::CSS_CYAN,
            Colors::DarkBlue => Rgb888::CSS_DARK_BLUE,
            Colors::DarkCyan => Rgb888::CSS_DARK_CYAN,
            Colors::DarkGoldenrod => Rgb888::CSS_DARK_GOLDENROD,
            Colors::DarkGray => Rgb888::CSS_DARK_GRAY,
            Colors::DarkGreen => Rgb888::CSS_DARK_GREEN,
            Colors::DarkKhaki => Rgb888::CSS_DARK_KHAKI,
            Colors::DarkMagenta => Rgb888::CSS_DARK_MAGENTA,
            Colors::DarkOliveGreen => Rgb888::CSS_DARK_OLIVE_GREEN,
            Colors::DarkOrange => Rgb888::CSS_DARK_ORANGE,
            Colors::DarkOrchid => Rgb888::CSS_DARK_ORCHID,
            Colors::DarkRed => Rgb888::CSS_DARK_RED,
            Colors::DarkSalmon => Rgb888::CSS_DARK_SALMON,
            Colors::DarkSeaGreen => Rgb888::CSS_DARK_SEA_GREEN,
            Colors::DarkSlateBlue => Rgb888::CSS_DARK_SLATE_BLUE,
            Colors::DarkSlateGray => Rgb888::CSS_DARK_SLATE_GRAY,
            Colors::DarkTurquoise => Rgb888::CSS_DARK_TURQUOISE,
            Colors::DarkViolet => Rgb888::CSS_DARK_VIOLET,
            Colors::DeepPink => Rgb888::CSS_DEEP_PINK,
            Colors::DeepSkyBlue => Rgb888::CSS_DEEP_SKY_BLUE,
            Colors::DimGray => Rgb888::CSS_DIM_GRAY,
            Colors::DodgerBlue => Rgb888::CSS_DODGER_BLUE,
            Colors::FireBrick => Rgb888::CSS_FIRE_BRICK,
            Colors::FloralWhite => Rgb888::CSS_FLORAL_WHITE,
            Colors::ForestGreen => Rgb888::CSS_FOREST_GREEN,
            Colors::Gainsboro => Rgb888::CSS_GAINSBORO,
            Colors::GhostWhite => Rgb888::CSS_GHOST_WHITE,
            Colors::Gold => Rgb888::CSS_GOLD,
            Colors::Goldenrod => Rgb888::CSS_GOLDENROD,
            Colors::Gray => Rgb888::CSS_GRAY,
            Colors::Green => Rgb888::CSS_GREEN,
            Colors::GreenYellow => Rgb888::CSS_GREEN_YELLOW,
            Colors::Honeydew => Rgb888::CSS_HONEYDEW,
            Colors::HotPink => Rgb888::CSS_HOT_PINK,
            Colors::IndianRed => Rgb888::CSS_INDIAN_RED,
            Colors::Indigo => Rgb888::CSS_INDIGO,
            Colors::Ivory => Rgb888::CSS_IVORY,
            Colors::Khaki => Rgb888::CSS_KHAKI,
            Colors::Lavender => Rgb888::CSS_LAVENDER,
            Colors::LavenderBlush => Rgb888::CSS_LAVENDER_BLUSH,
            Colors::LawnGreen => Rgb888::CSS_LAWN_GREEN,
            Colors::LemonChiffon => Rgb888::CSS_LEMON_CHIFFON,
            Colors::LightBlue => Rgb888::CSS_LIGHT_BLUE,
            Colors::LightCoral => Rgb888::CSS_LIGHT_CORAL,
            Colors::LightCyan => Rgb888::CSS_LIGHT_CYAN,
            Colors::LightGoldenrodYellow => Rgb888::CSS_LIGHT_GOLDENROD_YELLOW,
            Colors::LightGray => Rgb888::CSS_LIGHT_GRAY,
            Colors::LightGreen => Rgb888::CSS_LIGHT_GREEN,
            Colors::LightPink => Rgb888::CSS_LIGHT_PINK,
            Colors::LightSalmon => Rgb888::CSS_LIGHT_SALMON,
            Colors::LightSeaGreen => Rgb888::CSS_LIGHT_SEA_GREEN,
            Colors::LightSkyBlue => Rgb888::CSS_LIGHT_SKY_BLUE,
            Colors::LightSlateGray => Rgb888::CSS_LIGHT_SLATE_GRAY,
            Colors::LightSteelBlue => Rgb888::CSS_LIGHT_STEEL_BLUE,
            Colors::LightYellow => Rgb888::CSS_LIGHT_YELLOW,
            Colors::Lime => Rgb888::CSS_LIME,
            Colors::LimeGreen => Rgb888::CSS_LIME_GREEN,
            Colors::Linen => Rgb888::CSS_LINEN,
            Colors::Magenta => Rgb888::CSS_MAGENTA,
            Colors::Maroon => Rgb888::CSS_MAROON,
            Colors::MediumAquamarine => Rgb888::CSS_MEDIUM_AQUAMARINE,
            Colors::MediumBlue => Rgb888::CSS_MEDIUM_BLUE,
            Colors::MediumOrchid => Rgb888::CSS_MEDIUM_ORCHID,
            Colors::MediumPurple => Rgb888::CSS_MEDIUM_PURPLE,
            Colors::MediumSeaGreen => Rgb888::CSS_MEDIUM_SEA_GREEN,
            Colors::MediumSlateBlue => Rgb888::CSS_MEDIUM_SLATE_BLUE,
            Colors::MediumSpringGreen => Rgb888::CSS_MEDIUM_SPRING_GREEN,
            Colors::MediumTurquoise => Rgb888::CSS_MEDIUM_TURQUOISE,
            Colors::MediumVioletRed => Rgb888::CSS_MEDIUM_VIOLET_RED,
            Colors::MidnightBlue => Rgb888::CSS_MIDNIGHT_BLUE,
            Colors::MintCream => Rgb888::CSS_MINT_CREAM,
            Colors::MistyRose => Rgb888::CSS_MISTY_ROSE,
            Colors::Moccasin => Rgb888::CSS_MOCCASIN,
            Colors::NavajoWhite => Rgb888::CSS_NAVAJO_WHITE,
            Colors::Navy => Rgb888::CSS_NAVY,
            Colors::OldLace => Rgb888::CSS_OLD_LACE,
            Colors::Olive => Rgb888::CSS_OLIVE,
            Colors::OliveDrab => Rgb888::CSS_OLIVE_DRAB,
            Colors::Orange => Rgb888::CSS_ORANGE,
            Colors::OrangeRed => Rgb888::CSS_ORANGE_RED,
            Colors::Orchid => Rgb888::CSS_ORCHID,
            Colors::PaleGoldenrod => Rgb888::CSS_PALE_GOLDENROD,
            Colors::PaleGreen => Rgb888::CSS_PALE_GREEN,
            Colors::PaleTurquoise => Rgb888::CSS_PALE_TURQUOISE,
            Colors::PaleVioletRed => Rgb888::CSS_PALE_VIOLET_RED,
            Colors::PapayaWhip => Rgb888::CSS_PAPAYA_WHIP,
            Colors::PeachPuff => Rgb888::CSS_PEACH_PUFF,
            Colors::Peru => Rgb888::CSS_PERU,
            Colors::Pink => Rgb888::CSS_PINK,
            Colors::Plum => Rgb888::CSS_PLUM,
            Colors::PowderBlue => Rgb888::CSS_POWDER_BLUE,
            Colors::Purple => Rgb888::CSS_PURPLE,
            Colors::Red => Rgb888::CSS_RED,
            Colors::RosyBrown => Rgb888::CSS_ROSY_BROWN,
            Colors::RoyalBlue => Rgb888::CSS_ROYAL_BLUE,
            Colors::SaddleBrown => Rgb888::CSS_SADDLE_BROWN,
            Colors::Salmon => Rgb888::CSS_SALMON,
            Colors::SandyBrown => Rgb888::CSS_SANDY_BROWN,
            Colors::SeaGreen => Rgb888::CSS_SEA_GREEN,
            Colors::Seashell => Rgb888::CSS_SEASHELL,
            Colors::Sienna => Rgb888::CSS_SIENNA,
            Colors::Silver => Rgb888::CSS_SILVER,
            Colors::SkyBlue => Rgb888::CSS_SKY_BLUE,
            Colors::SlateBlue => Rgb888::CSS_SLATE_BLUE,
            Colors::SlateGray => Rgb888::CSS_SLATE_GRAY,
            Colors::Snow => Rgb888::CSS_SNOW,
            Colors::SpringGreen => Rgb888::CSS_SPRING_GREEN,
            Colors::SteelBlue => Rgb888::CSS_STEEL_BLUE,
            Colors::Tan => Rgb888::CSS_TAN,
            Colors::Teal => Rgb888::CSS_TEAL,
            Colors::Thistle => Rgb888::CSS_THISTLE,
            Colors::Tomato => Rgb888::CSS_TOMATO,
            Colors::Turquoise => Rgb888::CSS_TURQUOISE,
            Colors::Violet => Rgb888::CSS_VIOLET,
            Colors::Wheat => Rgb888::CSS_WHEAT,
            Colors::White => Rgb888::CSS_WHITE,
            Colors::WhiteSmoke => Rgb888::CSS_WHITE_SMOKE,
            Colors::Yellow => Rgb888::CSS_YELLOW,
            Colors::YellowGreen => Rgb888::CSS_YELLOW_GREEN,
        }
    }
}
