use embedded_graphics::geometry::{Angle, AngleUnit};

use crate::{
    controller::Editable,
    flight_physics::GliderData,
    system_of_units::{FloatToSpeed, Speed},
    AirSpeed, Density,
};

/// Flymode display variants
///
/// Flymode::Circling is displayed while circling upwind. In addition to vario signal and wind,
/// the average climb is also displayed.
///
/// In Flymode::StraightFlight the mean climb is hidden and the speed command is displayed
/// graphically and as a number.#[repr(u8)]
#[repr(u8)]
pub enum FlyMode {
    Circling,
    StraightFlight,
}

#[repr(u8)]
pub enum VarioMode {
    Vario,
    SpeedToFly,
}

#[repr(u8)]
pub enum EditMode {
    Section,
    Fullscreen,
}

#[repr(u8)]
pub enum DisplayActive {
    Vario,
}

/// Measured Values
///
/// This structure contains all variables that are generated by the Larus sensor box.
pub struct Measured {
    pub average_climb_rate: Speed,
    pub average_wind_angle: Angle,
    pub average_wind_speed: Speed,
    pub climb_rate: Speed,
    pub density: Density,
    pub wind_angle: Angle,
    pub wind_speed: Speed,
    pub airspeed: AirSpeed,
}

impl Default for Measured {
    #[allow(unused)]
    fn default() -> Self {
        Measured {
            average_climb_rate: 1.1.m_s(),
            average_wind_angle: 80.0.deg(),
            average_wind_speed: 15.0.km_h(),
            climb_rate: 1.7.m_s(),
            density: Density::AT_NN(),
            wind_angle: 66.0.deg(),
            wind_speed: 18.0.km_h(),
            airspeed: AirSpeed::from_tas_at_nn(100.0.km_h()),
        }
    }
}

/// Metastructure for different modes
pub struct Control {
    pub display_active: DisplayActive,
    pub fly_mode: FlyMode,
    pub vario_mode: VarioMode,
    pub edit_mode: EditMode,
    pub edit_var: Editable,
    pub edit_ticks: u32,
    pub glider_idx: i32,
    pub demo_acitve: bool,
}

impl Default for Control {
    fn default() -> Self {
        Self {
            display_active: DisplayActive::Vario,
            fly_mode: FlyMode::Circling,
            vario_mode: VarioMode::Vario,
            edit_mode: EditMode::Section,
            edit_var: Editable::ClimbRate,
            edit_ticks: 0,
            glider_idx: 104,
            demo_acitve: true,
        }
    }
}

/// Metastructure for calculated or set values
pub struct Calculated {
    pub mc_cready: Speed,
    pub speed_to_fly: AirSpeed,
    pub speed_to_fly_dif: Speed,
    pub thermal_climb_rate: Speed,
    pub volume: i8,
}

impl Default for Calculated {
    #[allow(unused)]
    fn default() -> Self {
        Calculated {
            mc_cready: 0.7.m_s(),
            speed_to_fly: AirSpeed::from_tas_at_nn(127.0.km_h()),
            speed_to_fly_dif: 3.0.km_h(),
            thermal_climb_rate: 1.3.m_s(),
            volume: 0,
        }
    }
}

/// Data model for the entire device
///
/// In the CoreModel all variables of the display are kept in a structure, which is used by
/// different modules. The CoreModel is filled by the CoreController, which holds the different
/// channels to the data sources like Larus, controls, sensors, inputs and time. The View
/// modules display the data contents. The LCD display and the sound system are the most
/// important ones.
#[derive(Default)]
pub struct CoreModel {
    pub calculated: Calculated,
    pub control: Control,
    pub measured: Measured,
    pub glider_data: GliderData,
}
