[package]
name = "vario_display"
version = "0.1.0"
edition = "2021"
publish = false
license = "MIT OR Apache-2.0"

[dependencies]
embedded-graphics = "0.8.0"
u8g2-fonts = "0.3.0"
micromath = { version = "1.1.0", default-features = false }
cortex-m = { version = "0.7", features = ["critical-section-single-core"]}
defmt = "0.3"
num = "0.4.0"
arrayvec = "0.7.4"

[features]
# Use knurling tools to log data
defmt = []
default = ["display_size_227x285"]
display_size_227x285 = []
