from webcolors import CSS3_NAMES_TO_HEX as color_dict
from webcolors import name_to_rgb, name_to_hex

# For the sequence
color_names = [
    'Black',
    'Dimgrey',
    'Grey',
    'Darkgrey',
    'Silver',
    'Lightgrey',
    'Gainsboro',
    'Whitesmoke',
    'White',

    'Darkslategrey',
    'Slategrey',
    'Lightslategrey',
    'Lightsteelblue',
    'Lavender',
    'Floralwhite',
    'Aliceblue',
    'Ghostwhite',
    'Honeydew',
    'Ivory',
    'Azure',
    'Snow',

    'Maroon',
    'Darkred',
    'Brown',
    'Firebrick',
    'Crimson',
    'Red',
    'Tomato',
    'Coral',
    'Indianred',
    'Lightcoral',
    'Darksalmon',
    'Salmon',
    'Lightsalmon',
    'Orangered',
    'Darkorange',
    'Orange',
    'Gold',
    'Darkgoldenrod',
    'Goldenrod',
    'Palegoldenrod',
    'Darkkhaki',
    'Khaki',
    'Olive',
    'Yellow',
    'Yellowgreen',
    'Darkolivegreen',
    'Olivedrab',
    'Lawngreen',
    'Chartreuse',
    'Greenyellow',
    'Darkgreen',
    'Green',
    'Forestgreen',
    'Lime',
    'Limegreen',
    'Lightgreen',
    'Palegreen',
    'Darkseagreen',
    'Mediumspringgreen',
    'Springgreen',
    'Seagreen',
    'Mediumaquamarine',
    'Mediumseagreen',
    'Lightseagreen',
    'Teal',
    'Darkcyan',
    'Aqua',
    'Cyan',
    'Lightcyan',
    'Darkturquoise',
    'Turquoise',
    'Mediumturquoise',
    'Paleturquoise',
    'Aquamarine',
    'Powderblue',
    'Cadetblue',
    'Steelblue',
    'Cornflowerblue',
    'Deepskyblue',
    'Dodgerblue',
    'Lightblue',
    'Skyblue',
    'Lightskyblue',
    'Midnightblue',
    'Navy',
    'Darkblue',
    'Mediumblue',
    'Blue',
    'Royalblue',
    'Blueviolet',
    'Indigo',
    'Darkslateblue',
    'Slateblue',
    'Mediumslateblue',
    'Mediumpurple',
    'Darkmagenta',
    'Darkviolet',
    'Darkorchid',
    'Mediumorchid',
    'Purple',
    'Thistle',
    'Plum',
    'Violet',
    'Magenta',
    'Orchid',
    'Mediumvioletred',
    'Palevioletred',
    'Deeppink',
    'Hotpink',
    'Lightpink',
    'Pink',
    'Antiquewhite',
    'Beige',
    'Bisque',
    'Blanchedalmond',
    'Wheat',
    'Cornsilk',
    'Lemonchiffon',
    'Lightgoldenrodyellow',
    'Lightyellow',
    'Saddlebrown',
    'Sienna',
    'Chocolate',
    'Peru',
    'Sandybrown',
    'Burlywood',
    'Tan',
    'Rosybrown',
    'Moccasin',
    'Navajowhite',
    'Peachpuff',
    'Mistyrose',
    'Lavenderblush',
    'Linen',
    'Oldlace',
    'Papayawhip',
    'Seashell',
    'Mintcream',
]

html_header = '''<!DOCTYPE html>
<html lang="de">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Webcolors</title>
    <style>
      h1 {font-family:sans-serif}
      table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
      }

      td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
      }

      tr:nth-child(even) {
        background-color: #dddddd;
      }
    </style>
  </head>
  <body>
    <header>
      <h1>WebColors</h1>
    </header>
    <table class="dtable">
      <thead>
        <tr>
          <th>Color</th>
          <th>Color Name</th>
          <th>RGB</th>
        </tr>
      </thead>
      <tbody>
'''

html_footer = '''      </tbody>
    </table>
  </body>
</html>
'''

with open("colors.rs", "w") as f:
    f.write("// generated by corlors.py\n\n")
    f.write("#[repr(u8)]\n")
    f.write("#[derive(PartialEq, Copy, Clone)]\n")
    f.write("pub enum Colors {\n")

    for idx, colorName in enumerate(sorted(color_names)):
        rgb = name_to_rgb(colorName.lower())
        colorDesc = f"// Rgb({rgb.red}, {rgb.green}, {rgb.blue})"
        color = colorName + f" = {idx},"
        f.write(f"    {color:30}{colorDesc}\n")

    f.write("}\n\n")
    f.write("use embedded_graphics::pixelcolor::{PixelColor, raw::RawU8};\n\n")
    f.write("impl PixelColor for Colors {\n")
    f.write("    type Raw = RawU8;\n")
    f.write("}\n")

with open("rgb565_colors.rs", "w") as f:
    f.write("// generated by corlors.py\n\n")
    f.write("use crate::Rgb565;\n\n")
    col_cnt = len(color_names)
    f.write(f"pub const RGB565_COLORS: [Rgb565; {col_cnt}] = [\n")

    for idx, colorName in enumerate(sorted(color_names)):
        rgb = name_to_rgb(colorName.lower())
        color = f"Rgb565::new({rgb.red}, {rgb.green}, {rgb.blue}), "
        colorDesc = f"// {idx:3} {colorName}"
        f.write(f"    {color:30}{colorDesc}\n")

    f.write("];\n")


with open('colors.html', 'w') as f:
    f.write(html_header)
    for col in color_names:
        rgb = name_to_rgb(col)
        rgb_desc = f"Rgb({rgb.red}, {rgb.green}, {rgb.blue})"
        hex_desc = name_to_hex(col)

        f.write(f'        <tr>\n')
        f.write(f'          <td style="background: {hex_desc};">&nbsp;</td>\n')
        f.write(f'          <td>{col}</td>\n')
        f.write(f'          <td>{rgb_desc}</td>\n')
        f.write(f'        </tr>\n')
    f.write(html_footer)
