// Generated by 'create_sprite_coords.py' - do not edit
#![allow(clippy::all)]

use super::PolarCoordinate;

pub const ARROW_PCOORDS: [PolarCoordinate; 7] = [
    PolarCoordinate {
        len: 0.5,
        alpha: -0.0,
    },
    PolarCoordinate {
        len: 0.3757658845611187,
        alpha: 0.4398425828157362,
    },
    PolarCoordinate {
        len: 0.34365680554879163,
        alpha: 0.1460122577112754,
    },
    PolarCoordinate {
        len: 0.5024937810560445,
        alpha: 3.0419240010986313,
    },
    PolarCoordinate {
        len: 0.5024937810560445,
        alpha: -3.0419240010986313,
    },
    PolarCoordinate {
        len: 0.34365680554879163,
        alpha: -0.1460122577112754,
    },
    PolarCoordinate {
        len: 0.3757658845611187,
        alpha: -0.4398425828157362,
    },
];

pub const WIND_ARROW_PCOORDS: [PolarCoordinate; 4] = [
    PolarCoordinate {
        len: 0.66,
        alpha: -0.0,
    },
    PolarCoordinate {
        len: 0.4220189569201838,
        alpha: 2.507569933926371,
    },
    PolarCoordinate {
        len: 0.0,
        alpha: 0.0,
    },
    PolarCoordinate {
        len: 0.4220189569201838,
        alpha: -2.507569933926371,
    },
];

pub const SCALE_MARKER_PCOORDS: [PolarCoordinate; 3] = [
    PolarCoordinate {
        len: 1.0143796901104953,
        alpha: -0.0582673029695334,
    },
    PolarCoordinate {
        len: 1.0143796901104953,
        alpha: 0.0582673029695334,
    },
    PolarCoordinate {
        len: 0.8776371308016877,
        alpha: -0.0,
    },
];

pub const SIMPLE_INDICATOR_PCOORDS: [PolarCoordinate; 3] = [
    PolarCoordinate {
        len: 1.2228915662650603,
        alpha: -0.0,
    },
    PolarCoordinate {
        len: 1.0118509561103022,
        alpha: -0.10736992203554742,
    },
    PolarCoordinate {
        len: 1.0118509561103022,
        alpha: 0.10736992203554742,
    },
];

pub const CLASSIC_INDICATOR_PCOORDS: [PolarCoordinate; 5] = [
    PolarCoordinate {
        len: 1.0,
        alpha: -0.0,
    },
    PolarCoordinate {
        len: 0.9335393173757407,
        alpha: 0.04051835247834694,
    },
    PolarCoordinate {
        len: 0.7026989039367824,
        alpha: 0.05384013197330247,
    },
    PolarCoordinate {
        len: 0.7026989039367824,
        alpha: -0.05384013197330247,
    },
    PolarCoordinate {
        len: 0.9335393173757407,
        alpha: -0.04051835247834694,
    },
];
