use crate::view::viewable::device_lineview::DeviceLineView;

pub const DEVICE_INFO_CONTENT: &[DeviceLineView] = &[
    // Vario Display
    DeviceLineView::Empty,
    DeviceLineView::Empty,
    DeviceLineView::Empty,
    DeviceLineView::VarioDisplay,
    DeviceLineView::DisplayVersion,
    DeviceLineView::SupplyVoltage,
    // DeviceLineView::IluminationVoltage,
    // DeviceLineView::TempPcb,
    DeviceLineView::InPinBreaks,
    DeviceLineView::InPinDrain,
    DeviceLineView::InPinGear,
    DeviceLineView::InPinSpeedToFly,
    DeviceLineView::OutPinFlash,
    // Sensor Box
    DeviceLineView::Empty,
    DeviceLineView::SensorBox,
    DeviceLineView::SensorboxVersion,
    DeviceLineView::GnssAccuracityOk,
    DeviceLineView::MagneticDisturbanceOk,
    DeviceLineView::AhrsPitch,
    DeviceLineView::AhrsRoll,
    DeviceLineView::AhrsYaw,
    DeviceLineView::Ias,
    DeviceLineView::Tas,
    DeviceLineView::Density,
    DeviceLineView::Gforce,
    DeviceLineView::GpsAltitude,
    DeviceLineView::GpsGroundSpeed,
    DeviceLineView::GpsTrack,
    DeviceLineView::GpsHeading,
    DeviceLineView::GpsSats,
    DeviceLineView::GpsState,
    DeviceLineView::GpsAccLen,
    DeviceLineView::GpsAccHeading,
    DeviceLineView::GnssBaseline,
    DeviceLineView::GnssBaseLen,
    DeviceLineView::GnssDown,
    DeviceLineView::AntSlaveRight,
    DeviceLineView::GnssRelNE,
    DeviceLineView::NickAngle,
    DeviceLineView::Pressure,
    DeviceLineView::SlipAngle,
    DeviceLineView::TurnRate,
    DeviceLineView::HorizonAvailable,
    DeviceLineView::Empty,
    DeviceLineView::Empty,
    DeviceLineView::Empty,
    DeviceLineView::Empty,
];
