[package]
authors = ["Simsys <winfried.simon@gmail.com>"]
edition = "2018"
readme = "README.md"
name = "vario"
version = "0.1.0"

[dependencies]
nb = "1"
embedded-hal = "0.2"
cortex-m = { version = "0.7", features = ["critical-section-single-core"]}
cortex-m-rt = "0.7"
panic-halt = "0.2"
stm32f4xx-hal = { version = "0.17", features = ["rt", "stm32f407", "fsmc_lcd", "can", "can1", "rtic"] }
bxcan = "0.7"

heapless = "0.7"
cortex-m-rtic = "1.1.4"
systick-monotonic = "1.0.1"
rtic-monotonic = "1.0.0"
fugit = "0.3"
static_cell = "1.2.0"

panic-probe = { version = "0.3", features = ["print-defmt"] }
defmt = "0.3"
defmt-rtt = "0.4"

display-interface = "0.4"
embedded-graphics = "0.8"
micromath = { version = "2.0", default-features = false }

[features]
defmt-default = []


[dependencies.vario_display]
path = "../../core"
features = ["display_size_227x285"]

[[bin]]
name = "vario"
test = false
bench = false

[profile.dev]
opt-level = 1
codegen-units = 16
debug = true
lto = false

[profile.release]
opt-level = "s"     # optimize for size
codegen-units = 1   # better optimizations
debug = true        # symbols are nice and they don't increase the size on Flash
lto = true          # better optimizations
